*** Variables ***
${INPUT_INSURER_CODE}            xpath=//*[@data-testid='input-insurer-code']
${INPUT_POLICY_NUMBER}           xpath=//*[@data-testid='input-policy-number']
${INPUT_PRODUCT_CODE}            xpath=//*[@data-testid='input-product-code']
${INPUT_INSURED_DOCUMENT}        xpath=//*[@data-testid='input-insured-document']
${INPUT_PREMIUM_AMOUNT}          xpath=//*[@data-testid='input-premium-amount']
${INPUT_COVERAGE_AMOUNT}         xpath=//*[@data-testid='input-coverage-amount']
${INPUT_EFFECTIVE_START_DATE}    xpath=//*[@data-testid='input-effective-start-date']
${INPUT_EFFECTIVE_END_DATE}      xpath=//*[@data-testid='input-effective-end-date']

${BTN_EMITIR}                    xpath=//*[@data-testid='btn-registrar']